"""SQLAlchemy ORM declarations for the analytics module (architecture.md §4.2).

Owns exactly four tables: ``operational_metrics_snapshots``,
``financial_roi_snapshots``, ``baseline_costs``, ``dashboard_exports``.

Interaction contract: no cross-module ORM ``relationship()`` is declared here
— ``repositories/analytics/repository.py`` is the only file that imports
these classes; every other module's data is read into these snapshot tables
only via ``services/analytics/service.py``'s aggregation calls into other
modules' repositories, never the reverse (no other module writes here). Per
``app/models/console/models.py``'s own documented interaction contract, every
other module's ``models.py`` references ``staff_users.id`` via a plain UUID
*foreign-key* column only (``entered_by_staff_id``, ``requested_by_staff_id``
below) — no cross-module ``relationship()`` and no import of
``StaffUser`` itself.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime

from sqlalchemy import Date, DateTime, Enum, ForeignKey, Integer, Numeric, String, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from app.common.enums import DashboardType, ExportFormat
from app.core.database import Base


class OperationalMetricsSnapshot(Base):
    """One computed value of one of the 6 RAR001 operational metrics for a
    given reporting period.

    FR-E9.1: ``baseline_value`` is ``NULLABLE`` — ``null`` means "baseline
    pending" (architecture.md §4.2 note), the one field that drives the
    ``data_delayed``/baseline-pending distinction on ``GET
    /analytics/operational``.
    """

    __tablename__ = "operational_metrics_snapshots"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    metric_name: Mapped[str] = mapped_column(String(100), nullable=False)
    metric_value: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)
    # FR-E9.1: null = "baseline pending" — never coerced to 0 or any sentinel.
    baseline_value: Mapped[float | None] = mapped_column(Numeric(12, 2), nullable=True)
    period_start: Mapped[date] = mapped_column(Date, nullable=False)
    period_end: Mapped[date] = mapped_column(Date, nullable=False)
    computed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class FinancialRoiSnapshot(Base):
    """One computed month's financial-ROI rollup (recovered appointments,
    recovered revenue, baseline cost, ROI%)."""

    __tablename__ = "financial_roi_snapshots"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    period_month: Mapped[date] = mapped_column(Date, nullable=False)
    recovered_appointments: Mapped[int] = mapped_column(Integer, nullable=False)
    recovered_revenue: Mapped[float] = mapped_column(Numeric(14, 2), nullable=False)
    baseline_cost: Mapped[float | None] = mapped_column(Numeric(14, 2), nullable=True)
    roi_percentage: Mapped[float | None] = mapped_column(Numeric(6, 2), nullable=True)
    computed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class BaselineCost(Base):
    """A clinic_management-entered baseline cost figure for a given period,
    used to compute ``financial_roi_snapshots.roi_percentage`` (audit-logged,
    T119 AC)."""

    __tablename__ = "baseline_costs"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    # Plain FK reference to staff_users.id (console module) -- no cross-module
    # relationship() declared, per the Interaction contract.
    entered_by_staff_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("staff_users.id"), nullable=False
    )
    amount: Mapped[float] = mapped_column(Numeric(14, 2), nullable=False)
    effective_period: Mapped[date] = mapped_column(Date, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class DashboardExport(Base):
    """A generated operational/financial dashboard export file (PDF/CSV).

    ``storage_uri`` points at the object-storage location of the generated
    file — the file itself, never its bytes, is stored here
    (``open_questions[Q-cf1e404b]``: owned by this file, generated by
    ``DashboardExportService.generate``)."""

    __tablename__ = "dashboard_exports"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    # Plain FK reference to staff_users.id (console module) -- no cross-module
    # relationship() declared, per the Interaction contract.
    requested_by_staff_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("staff_users.id"), nullable=False
    )
    dashboard_type: Mapped[DashboardType] = mapped_column(
        Enum(DashboardType, native_enum=False, length=20), nullable=False
    )
    format: Mapped[ExportFormat] = mapped_column(
        Enum(ExportFormat, native_enum=False, length=10), nullable=False
    )
    date_range_start: Mapped[date] = mapped_column(Date, nullable=False)
    date_range_end: Mapped[date] = mapped_column(Date, nullable=False)
    storage_uri: Mapped[str] = mapped_column(String(500), nullable=False)
    requested_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
